### ISSUE TITLE
Game Proposal: Tempest

### ISSUE THREAD

**Issue by pserwylo** [retrowars/retrowars#10]
**Name**

Tempest

**Description**

[Tempest Wikipedia article](https://en.wikipedia.org/wiki/Tempest_(video_game))

The player is looking down a 3D "pipe" (for lack of a better word) of various shapes and sizes. They cling to the edge of the pipe and traverse around the circumference, as monsters climb from the end to the front of this "pipe". From any position, the player can shoot at monsters in front of them. When monsters get to the end of the pipe, they walk around the circumference for a brief period (and hence the player risks running into them) for a brief period.

**Links to screenshots / videos / descriptions**

Gameplay video - [Youtube](https://www.youtube.com/watch?v=jfaCrdBABUY)

**Multiplayer Handicap**

* More creatures spawn at the start of the tunnel each time other players score.

**Comment by pserwylo** [comment]
Great, this has the most votes, and soon I'll be looking at adding another game, so Tempest it is!!! Thanks for voting everyone.

For those interested, I'm just working on an internet game server to let people around the world play (rather than just via the local network). See #7 for more details.

When I get around to working on Tempest, would anybody be interested in a blog of how the progress goes? I'm hoping that doing so would be useful to others embarking on either: Game development, learning Kotlin, learning libgdx, etc.

**Comment by Offliner33** [comment]
Will the server software be available for anyone to use?

Also, yes, I would love to see such a blog.

**Comment by pserwylo** [comment]
Absolutely @Offliner33, thatis a keypillar of my thinking. Here are my thoughts on it: https://peter.serwylo.com/2021/07/03/sustainable-server-infra-for-open-source-games

**Comment by pserwylo** [comment]
Okay, here we go. This game is underway now, but will be a little slower than planned because I'm quite enjoying writing English at the same time I write code :)

https://peter.serwylo.com/2021/08/01/let-the-community-decide-the-next-retro-game
https://peter.serwylo.com/2021/08/01/tempest-initial-skeleton#displaying-a-message-at-the-start-of-the-game

**Comment by pserwylo** [comment]
First three levels, no 3rd dimension, no enemies, no shooting, no scoring. But progress nontheless :)

https://peter.serwylo.com/2021/08/02/tempest-basic-progress


https://user-images.githubusercontent.com/248565/127787123-d2884247-4e47-445f-808b-b4ce8bb585fc.mp4

**Comment by pserwylo** [comment]
And now a 3rd dimension...

https://peter.serwylo.com/2021/08/03/tempest-basic-3d

https://user-images.githubusercontent.com/248565/127793245-091f7016-9568-4fb7-bc54-2ae430d3bad0.mp4

![tempest-perspective](https://user-images.githubusercontent.com/248565/127793258-c3781d0f-f5d1-430c-b1ea-ef95bbc0dd8e.png)

**Comment by pserwylo** [comment]
[v0.13.3 released]. Tempest now supports:

* Spikes and corresponding "spike builder" enemies (starting at level 3)
* Careful to avoid spikes when transitioning from the end of one level until the start of the next.

https://user-images.githubusercontent.com/248565/142749866-f3288017-17d9-4e6b-a0df-0fe984be18dd.mp4

Next on my list of things to do is to support rapid firing by holding down fire (but limiting the number of bullets on screen to 8 as per the original). This should help with the RSI that I seem to be getting from play testing this :)

**Comment by pserwylo** [comment]
Rapid firing now supported in [v0.13.4](https://github.com/retrowars/retrowars/releases/tag/0.13.4). From my personal perspective, this makes the game so much more fun. It is far less about smashing buttons as fast as possible, and much more about navigating the level strategically to avoid getting over awed by enemies.

**Comment by pserwylo** [comment]
Okay, safe to say that this is now live and able to be played by all F-Droid and Google Play users with v0.14.0 of retrowars. Thanks for following along (and apologies for letting the blog slide). Feel free to report any feedback here - is it balanced enough? Too easy? Too hard? Especially interested in if you think it is unfairly easy/hard compared to other multiplayer games.
