### ISSUE TITLE
Pause across all games

### ISSUE THREAD

**Issue by AnonymousSeal** [retrowars/retrowars#11]
Very simple but vital request:

A pause feature to be able to pause the game. (At least in Single Player Mode)

**Comment by pserwylo** [comment]
Yes, very good idea. Thanks for the recommendation. You are also right that this will only work in single player mode. Though if it brings up a menu with which the user can change options - in the future may be sound, etc, then it perhaps could be overlayed on top of the (still running) multiplayer game. Would provide a nice interface for the player to quite if they have to leave the game.

You may or may not be aware that I've lifted most of the UI from my [Beat Feet](https://github.com/beat-feet/beat-feet) game, which does support a transparent pause screen overlayed on the game, so we'll probably do something similar here.

**Comment by pserwylo** [comment]
This worked out okay and seems to work across all games (single player only of course):

![image](https://user-images.githubusercontent.com/248565/163093173-af661257-2610-483e-b678-a1917751655d.png)

Will release #72 in the coming days for F-Droid to build and release in the next week or so. Please provide any feedback when you see this released.

Future plans: Multiplayer will also have a menu, but it wont pause the underlying game for obvious reasons. It will allow things like quitting the game (currently quite cumbersome) and perhaps toggling sound when #41 is implemented.

**Comment by pserwylo** [comment]
Bugger it, here is a multiplayer menu too for some level of consistency (and because it irks me I can't easily and gracefully leave a game right now). Will go out with the same PR mentioned above.

![image](https://user-images.githubusercontent.com/248565/163166221-f99b45aa-8042-4983-a657-ddb024cb081a.png)

**Comment by JM480** [comment]
This issue can be closed now since this feature has been added.

**Comment by pserwylo** [comment]
@JM480 - thanks for the heads up. Hope you like the pause screen. I appreciate you helping tidy up these issues - would you like me to add you as a "reporter" to this project so that you have permission to rename/edit/close issues? Completely optional, no pressure.

**Comment by JM480** [comment]
> @JM480 - thanks for the heads up. Hope you like the pause screen. I appreciate you helping tidy up these issues - would you like me to add you as a "reporter" to this project so that you have permission to rename/edit/close issues? Completely optional, no pressure.

I'd prefer to let you decide whether or not issues should be closed. I'll just remind you if there is an issue that probably should be closed.

**Comment by pserwylo** [comment]
No worries. Thanks!
