### ISSUE TITLE
Upgrade Ktor version 2.x.x support

### ISSUE THREAD

**Issue by ronjunevaldoz** [retrowars/retrowars#119]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pserwylo** [comment]
Thanks for filing this issue. I'd be happy to accept a PR supporting this, but given the server code is semi-stable now, it is not a high priority for me to bump the verson of ktor. Thanks.
