### ISSUE TITLE
Options aren't saved

### ISSUE THREAD

**Issue by AnonymousSeal** [retrowars/retrowars#13]
Options aren't saved, so they reset when reopening the app.

1. Go to options
2. Turn off gratuitous visual effects
3. Close the app
4. Reopen it

Gratitous visual effects are on again

**Comment by pserwylo** [comment]
Good pick up, thanks for the report. I've noticed this too, and I believe v0.2.0 will address it when released [via this commit](https://github.com/retrowars/retrowars/commit/ad4a6921077714258bf0917a2f13689211df74cf#diff-284eaa2d5259d59ff3d50aa48f8c8a94cb98d477399af6b42a981b0e3d848ed0).
