### ISSUE TITLE
Game Proposal: [...]

### ISSUE THREAD

**Issue by Kennyston** [retrowars/retrowars#154]
**Name**

(Use the name of the original game)

**Description**

(Include the year it was published, the consoles it was available on, and any other information that helps set the scene for why this would fit alongside other games in Super Retro Mega Wars. The more detail you can provide about the mechanics of the game the better.)

**Links to screenshots / videos / descriptions**

(Add links to any relevant YouTube videos, screenshots, etc which help to showcase how the original game plays)

**Multiplayer Handicap**

(In order to play against other games in Super Retro Mega Wars, we need to know how to do two main things - handicap the current player when other games send events to this game, and send events to other games when we score in this game. Sending events to others is simple, all games do it automatically every time a certain number of points are scored. Handicapping the current player is unique to each game - e.g. in Asteroids new asteroids appear on the screen, in Missile Command missiles appear on the screen)

**Comment by inson1** [comment]
@pserwylo @Kennyston  Please delete this spam

**Comment by pserwylo** [comment]
Thanks @inson1. Would you like to have ["Triage" permissions](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization) for retrowars? It is always nice to have more than just me chipping in on the issue list. If you say yes, there would be no obligation to actually do anything to manage these issues, but I'd be happy for there. If you say no, I will also not be offended!
