### ISSUE TITLE
Game Proposal: Breakout

### ISSUE THREAD

**Issue by pserwylo** [retrowars/retrowars#23]
**Name**

Breakout

**Description**

Breakout was released in 1976 by Atari.

There are numerous variations throughout history. Some of the ones I played growing up (in chronological order) include:
* Aquanoid
* Arkanoid
* Block Breaker
* DX Ball
* Ricochet

Alas, I never actually played the original that I am proposing here!!!

Of course, there are many more in between, each with their own slant. The proposal here is to go for the original one, because it will fit in best with the simplicity of the other games here. In the future, perhaps it can stray towards something more complex or modern.

Controls:
* Use the touch screen controls to drag the paddle left or right. If this proves to be too easy, then use soft buttons on the screen to move left or right when holding the buttons.

**Links to screenshots / videos / descriptions**

* [Wikipedia article](https://en.wikipedia.org/wiki/Breakout_(video_game))
* [YouTube playthrough](https://youtu.be/AMUv8KvVt08?t=188)

**Multiplayer Handicap**

A few suggestions:
* Add additional blocks to the screen in random locations. If the screen is already full of blocks, just keep adding them below the normal starting row of blocks.
* Speed up the ball (but does it speed up forever until the speed of light?)
* Reduce the size of the paddle (but does it shrink forever until it is gone?)

**Comment by Efreak** [comment]
Bananoid style - game board is later than screen and requires horizontal scrolling

**Comment by pserwylo** [comment]
Okay, with Space Invaders scheduled to be released with multiplayer support over the coming days, this is now the resounding next highest voted game to be implemented. Looking forward to having a breakout clone implemented in Super Retro Mega Wars? Keep an eye on this issue for updates!

**Comment by pserwylo** [comment]
And we're under way. 
First thought was an on-screen controller with left/right buttons, but I think it may work better to just use touch sensitive controls (missile command uses this to great effect):

https://user-images.githubusercontent.com/248565/165028751-8149077b-ff6d-45a3-a092-0e103ae853e9.mp4

**Comment by pserwylo** [comment]
v0.28.0 tagged, ready for F-Droid to build and release. Includes the first (non-multiplayer) version of our breakout clone:


https://user-images.githubusercontent.com/248565/166130806-6d2de815-ad97-4b00-97c4-a6ed07296b10.mp4

The main issue is that when using your finger to guide the paddle, you can't see where the paddle is because your hand obscures the view. Will contemplate perhaps casting a "shadow" upwards to tell you where the paddle is, or perhaps moving the paddle higher (though I think that will be a bit odd).

**Comment by pserwylo** [comment]
Finished! F-Droid has built v0.29.0, and will release it in a day or two. Please do check it out, update to the latest version, and see if it is fun and fair to play both in single player and multiplayer!
