### ISSUE TITLE
More white-black contrast

### ISSUE THREAD

**Issue by mikelgs1** [retrowars/retrowars#24]
**Is your feature request related to a problem? Please describe.**
I cant see properly sometimes, objects are too thin and vague sometimes, specially when my phone screen reflects sunlight.

**Describe the solution you'd like**
I really like the actual style, so I would add a "more contrast" option in the settings, in order to have the option when it is needed.

**Describe alternatives you've considered**
Outlines of the objects could be bolder. That would be probably enough, since white-darkgrey and red-darkgrey make a good contrast.

**Additional context**
It is not my case, but there are people with color blindness and so on. Maybe it is a good idea to give it a thought.

Anyways, this was an idea that occurred to me. Truth is that the game (game platform actually!) is already a success in my opinion. Congratulations!!

**Comment by pserwylo** [comment]
Hi, thanks for the feedback (and the kind words). Apologies for not acknowledging earlier, but I really liked the idea and finally got around to it in v0.15.0. It has been tagged, and F-Droid will build and release it soon. Keep an eye out in the coming week. Thanks!

**Comment by mikelgs1** [comment]
Thank you!!

**Comment by pserwylo** [comment]
No problem. FYI here is a screenshot:

![Screenshot_20211213_132408_com serwylo retrowars](https://user-images.githubusercontent.com/248565/145742783-3658f0d9-4b0b-4492-95f8-1ff96d3affb2.jpg)
