### ISSUE TITLE
Tetris: Can drop a block into another block or crash the app

### ISSUE THREAD

**Issue by pssandhu** [retrowars/retrowars#27]
**Describe the bug**
If the drop button is pressed at the correct moment a block can be placed one row inside the blocks beneath it. The app crashes if there is no block underneath.

**To Reproduce**
1. Wait until a block naturally falls into its final place
2. Press the drop button before the next block spawns
3. If there is already a block underneath, it placed one row deeper than should be possible
4. If on the bottom row, the app crashes

**Expected behavior**
Nothing/skip to next block spawning

**Smartphone:**
 - Android Version: 8.0.0
 - Version: 0.6.1

**Additional context**
Only tested on singleplayer.
From a quick look at the code the problem might the `+1` in the loop condition. Might also need to check for a legal move before `storeTetronimoInGrid`:

https://github.com/retrowars/retrowars/blob/3c245c4902fa15b5973282f6e7e5bce5e5334c87/core/src/com/serwylo/retrowars/games/tetris/TetrisGameScreen.kt#L158-L163

Can also teleport through blocks if the `newY + 1` position is valid and continue dropping.

**Comment by pserwylo** [comment]
Can I just say, this is an exceptionally well written bug report, thanks so much for the detail. Very easy to see where the issue is now. 

Would you like to have a crack at fixing it? If not I can address it in the coming days.

**Comment by pssandhu** [comment]
That's good to hear! I don't have much experience with android development or submitting pull requests but I'll give it a go.
