### ISSUE TITLE
Game Proposal: Tetris

### ISSUE THREAD

**Issue by pserwylo** [retrowars/retrowars#8]
**Name**

Tetris

**Description**

[Tetris gameplay - from tetris.wiki](https://tetris.wiki/Gameplay_of_Tetris)

Probably doesn't need much introduction, but things worthy of discussion are that later versions of tetris made certain features more standard, so we should decide which of the following to implement (though the first version will likely have none of these newer additional features):

* [Instant drop / soft drop](https://tetris.wiki/Drop) - Allowing you to drop the piece instantly and then a short [lock delay](https://tetris.wiki/Lock_delay) which allows the player to move left/right briefly before the piece is locked in place.
* [Ghost pieces](https://tetris.wiki/Ghost_piece) show where the piece will land in a faint colour.
* [Hold](https://tetris.wiki/Hold_piece) allows players to temporarily store the current piece off to the side in the hope of finding a better piece later.

**Links to screenshots / videos / descriptions**

* GameBoy Tetris - the version I grew up on and is most familiar to me - [Youtube](https://www.youtube.com/watch?v=BQwohHgrk2s)
* 2 player Tetris on the original GameBoy version - [Youtube](https://www.youtube.com/watch?v=hfANfIG5xps).
* Evolution of Tetris - [Youtube](https://www.youtube.com/watch?v=E5r9GDwkMpY) - This is a bit of overkill, but you can see that towards the later versions, certain features become more standard, including showing the ghost of where the piece will land, instantly dropping the piece, showing more than one of the next pieces, holding pieces, etc.

**Multiplayer Handicap**

The original GameBoy Tetris had a multiplayer mode (yes - via a link cable!) whereby scoring lines on one screen would place the same number of lines at the bottom of the other players screen. Of course, you cannot place a full line, there needs to be at least one hole in it so that the line can be cleared eventually. It also seemed to do it nicely - that is to say that it lined up this single empty cell with a clear column above it if there was one available. 

(The original game also showed each player how high each other players stack was. We can use this to broadcast to othe rplayers in retrowars how much pressure a player is under because Tetris doesn't have lives or cities like asteroids or missile command).

**Comment by pserwylo** [comment]
This has now been implemented and will be released in v0.2.0 of retrowars (to be tagged once F-Droid builds and releases the initial version).

**Comment by AnonymousSeal** [comment]
really looking forward to the next release :)

**Comment by pserwylo** [comment]
This has now been released and is available via F-Droid. There is a bug where it doesn't send scores to the server during multiplayer, but it works in single player as expected. v0.3.0 fixes this bug and will be built and released by F-Droid as the buildbot gets to it.
