### ISSUE TITLE
Pac-man!

### ISSUE THREAD

**Issue by KalelTonatiuh** [retrowars/retrowars#83]
Or make one similar ti pac man.

**Comment by pserwylo** [comment]
Thanks for the recommendation. Closing as a duplicate of #18, but be sureto put a thumbs up on that request to ensure it is the most popular. 

Right now I'm working on Breakout (#76), but Pac-Man is definitely next most popular right now: https://github.com/retrowars/retrowars/issues?q=is%3Aopen+label%3Agame-proposal+sort%3Areactions-%2B1-desc
